- import_playbook: common.yml
- import_playbook: dns_master.yml
- import_playbook: dns_slave.yml
- import_playbook: postfix.yml
- import_playbook: webserver.yml
- import_playbook: nginx_proxy.yml
- import_playbook: vyos_gateway.yml
- import_playbook: docker_container.yml
